### ISSUE TITLE
Improve layout

### ISSUE THREAD

**Issue by tvdk-sudoku** [EddieTheEd/demeter#5]
For example, remove dead space from the top bar, to increase the space for the info/timer/notes areas.  
Maybe also make the info/timer/notes areas toggleable pop-ups to increase space for the file. For example, add a button for each, which when pressed, opens up that pop-up, then something like:
![image](https://github.com/EddieTheEd/demeter/assets/85726678/387d73bb-b04c-410d-8717-52fa01060cff)

<br><br><br><br>

![image](https://github.com/EddieTheEd/demeter/assets/85726678/5ccb50e2-a055-4f89-b65f-23e30d4b01fd)

**Comment by EddieTheEd** [comment]
you're such a css tory

**Comment by EddieTheEd** [comment]
done!
