### ISSUE TITLE
Change the button checkboxes to buttons

### ISSUE THREAD

**Issue by tvdk-sudoku** [EddieTheEd/demeter#6]
![image](https://github.com/EddieTheEd/demeter/assets/85726678/ce499a4d-4af7-4929-aa8e-c9974cb5bc40)
![image](https://github.com/EddieTheEd/demeter/assets/85726678/083db5e1-43b1-4a7d-adf6-4f8a7021cdc9)

**Comment by EddieTheEd** [comment]
if you want it so much you do it
