### ISSUE TITLE
Files not loading

### ISSUE THREAD

**Issue by tvdk-sudoku** [EddieTheEd/demeter#7]
Sometimes when you click a file, it opens it, but doesn't load. The same is true for when the webpage is first loaded, and the instructions page opens, but doesn't load.

![image](https://github.com/EddieTheEd/demeter/assets/85726678/abb94018-b669-468e-8c55-caa707fff534)

**Comment by EddieTheEd** [comment]
Google Docs viewer's fault not mine

**Comment by tvdk-sudoku** [comment]
You can still improve it
